env:
  global:
    - secure: aVllqg77RGbdcnEIIWqiiJxQx+3hhipgDzlxZT9lgwgLw4WRWffvXAOJszL9s3+z0Iyp3mw8w/hKwYtudhuXgRBlGMb1c37YEt5W/DnWDZMtzl4kDLmeSAalTfSzOfDpzs9qcZ1/Zc1i5/NKC0fkA8SE+haENo+mwkRLuc/njfBrfSYUno6amO3I2MbkrX+2VyewGuIjfbNuKCwRt+nYHS8h5zxYSedxFG9aUfrSQsOi3HRWDJQzul5QNs0i8k/VWe7sdyQwPCI+FPqtaAytCgtrKp9nHg0LMGgHfONYF6tI3RUGNqMcDpBumkKodBPk1FltODhjxRYum9yZ4PlgpnSzunfRQ/Gt7+tRJLWPCBgQdLh4amdqhB98T/CZeZZkw87WkNQK1mjiyCgEzLbmy5I1vBJxkzoMcGYTXukv7oGOa5aSk5AkvnLZb6LYPa8/BYUuA1BQIpbB4jih22JmvkvJIZEw410+GKYhekVFSbdgqxcwBUYpHJ76dScXiM8TTeK7iEKow8cTdPJLoYHhSw4U8sAar3HzilUCcuzCFvz5vj/qI4kVDQEmF7G7kcCUFoDNur0QP1WEjycsaP6sZFZivBu1H8W+gjXbsfHA1kHVjk9Yjkcv9KYCO4LHwjH5RYQVdpL1RUgGdQON5S5FKhYTI8LcWrNFsORQMcUsF7U=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/smed79_blocklist_facebook
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
