env:
  global:
    - secure: fBrsdaE6aSfhlZ99cpg0OowGPzFLbSVlK9DckAg1kZV1R5HX1FtGGegcZI90R1pNRzonbnoLB8cJfkdWRsYbD5+Fqj+ePWtWSIDp6INO444x/OhbdDhVYmybohc1bzsD17DNKoQeN5Kj3LZSRr5y2kzFFqN7aeStv4bbLG6jxXrRjU7YpiPgAczQjRKLNOVCZgIXSYzePDsARqSUPZdpKoEP+PG8aqliN3u9AWf3ofpfMntmtSAQlQI6BLWFD/Ycm+8vSjxka3ftNxHredqc7nwNHiik7lufeheF70izU2ueDk6J04m2vKGPcBuNT+l4p24317f4CGfYl4OmN1Rbiq9Mdh/zNxTY/8i3HWI7PdekOfCiBWv1qgZmMRuNohADQdepvVFCNl3CM1ZLOPNS2xQqtHU3PeTpWKaqGVUgVQuWyBRJfud4LUn4P5vILK/pffKELDdDUnN0MuvqWT1/nYCKNiwMxGl7b/4CCk9UFFNbM9b1wBSvMHkSAjfZDOvMobrerKGIdmw6c61DAoGazTBH4EWU3sN9QVA9+dL9DTG+oHaJymaPdt4VNGoPPUWTC3Zaylumkpl3anz8dcW5RvXthYFh0myZCcXzfjndqYAE2GPY9R9jktpI3qMadr52cdL0kff1G9nX/tVowJSdFlH8jR/671XbNscXLclaFX4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/smed79_blocklist_facebook
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
